spring.application.name=backend
#segredo para token gerado no powershell
jwt.secret=Vn9m3+W6k0Yh5n2Y4M6XkJb+z0P2J5r0P0FJcP4A8w8=
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=8MB
spring.servlet.multipart.max-request-size=2MB
file.upload-dir=uploads
spring.data.web.pageable.default-page-size=10
